global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'webapp'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8000']
    scrape_interval: 30s

  - job_name: 'nginx'
    metrics_path: /health
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

